services:
  - type: web
    name: burrowed-magazine-api
    env: docker
    dockerfilePath: ./Dockerfile
    plan: free
    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: "False"
      - key: ALLOWED_HOSTS
        value: burrowed-magazine-api.onrender.com
      - key: AWS_ACCESS_KEY_ID
        value: YOUR_ACCESS_KEY_ID
      - key: AWS_SECRET_ACCESS_KEY
        value: YOUR_SECRET_ACCESS_KEY
      - key: AWS_STORAGE_BUCKET_NAME
        value: burrowed-magazine-media
      - key: AWS_S3_REGION_NAME
        value: ap-south-1
