services:
  - type: web
    name: woodtech-backend
    env: docker
    dockerfilePath: ./Dockerfile
    plan: free
    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: "False"
      - key: ALLOWED_HOSTS
        value: woodtech-backend.onrender.com
      - key: AWS_ACCESS_KEY_ID
      - key: AWS_SECRET_ACCESS_KEY
      - key: AWS_STORAGE_BUCKET_NAME
        value: burrowed-magazine-media
      - key: AWS_S3_REGION_NAME
        value: ap-south-1
      - key: DATABASE_URL
        fromDatabase:
          name: burrowed-db
          property: connectionString
