# Generated by Django 5.2.1 on 2025-05-17 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Magazine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('date_uploaded', models.DateTimeField(auto_now_add=True)),
                ('volume_number', models.PositiveIntegerField(editable=False)),
                ('season_number', models.PositiveIntegerField(editable=False)),
                ('pdf_file', models.FileField(upload_to='magazines/')),
                ('description', models.TextField(blank=True, null=True)),
                ('is_published', models.BooleanField(default=False)),
            ],
        ),
    ]
