# Generated by Django 5.2.1 on 2025-05-17 19:29

import woodtech.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('woodtech', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='magazine',
            name='cover_image',
            field=models.ImageField(blank=True, null=True, upload_to=woodtech.models.magazine_cover_upload_path),
        ),
        migrations.AlterField(
            model_name='magazine',
            name='pdf_file',
            field=models.FileField(upload_to=woodtech.models.magazine_pdf_upload_path),
        ),
    ]
