# Generated by Django 5.2.1 on 2025-07-12 09:18

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('woodtech', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='magazine',
            name='date_uploaded',
            field=models.DateTimeField(default=django.utils.timezone.now, help_text='Date when this item was uploaded', verbose_name='Upload Date'),
        ),
    ]
