# Generated by Django 5.2.1 on 2025-05-18 16:36

import woodtech.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('woodtech', '0002_magazine_cover_image_alter_magazine_pdf_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='magazine',
            name='cover_image',
            field=models.ImageField(blank=True, null=True, upload_to=woodtech.models.magazine_cover_upload_path, validators=[woodtech.models.validate_image]),
        ),
        migrations.AlterField(
            model_name='magazine',
            name='pdf_file',
            field=models.FileField(upload_to=woodtech.models.magazine_pdf_upload_path, validators=[woodtech.models.validate_pdf]),
        ),
    ]
