# Generated by Django 5.2.1 on 2025-10-22 19:05

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('woodtech', '0002_alter_magazine_date_uploaded'),
    ]

    operations = [
        migrations.CreateModel(
            name='SeasonalSubmissionConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('season', models.CharField(choices=[('Spring', 'Spring'), ('Summer', 'Summer'), ('Fall', 'Fall'), ('Winter', 'Winter')], max_length=20)),
                ('year', models.PositiveIntegerField()),
                ('is_active', models.BooleanField(default=False)),
                ('theme_title', models.CharField(max_length=200)),
                ('theme_description', models.TextField(blank=True, null=True)),
                ('seasonal_note', models.TextField(blank=True, null=True)),
                ('submission_deadline', models.DateField()),
                ('publication_date', models.DateField()),
                ('theme_alignment', models.TextField(blank=True, help_text='Short paragraph about how submissions should align with the current theme.', null=True)),
                ('theme_guidance_intro', models.TextField(blank=True, help_text='Introductory paragraph for theme guidance (optional).', null=True)),
                ('theme_bullet_1', models.CharField(blank=True, help_text='Bullet point 1 (e.g., Stories of deep devotion...)', max_length=300, null=True)),
                ('theme_bullet_2', models.CharField(blank=True, help_text='Bullet point 2', max_length=300, null=True)),
                ('theme_bullet_3', models.CharField(blank=True, help_text='Bullet point 3', max_length=300, null=True)),
                ('theme_bullet_4', models.CharField(blank=True, help_text='Bullet point 4', max_length=300, null=True)),
                ('theme_bullet_5', models.CharField(blank=True, help_text='Bullet point 5', max_length=300, null=True)),
                ('current_issue_label', models.CharField(blank=True, help_text="Human-readable issue label, e.g. 'Year 1 - Fall 2025'.", max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TokenUsage',
            fields=[
                ('ip_address', models.CharField(max_length=45, primary_key=True, serialize=False)),
                ('tokens_used', models.IntegerField(default=0)),
                ('last_updated', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'token_usage',
                'indexes': [models.Index(fields=['last_updated'], name='token_usage_last_up_6ce0dc_idx')],
            },
        ),
    ]
