# Generated by Django 5.2.1 on 2025-10-24 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('woodtech', '0003_seasonalsubmissionconfig_tokenusage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='seasonalsubmissionconfig',
            name='current_issue_label',
        ),
        migrations.RemoveField(
            model_name='seasonalsubmissionconfig',
            name='theme_description',
        ),
        migrations.AddField(
            model_name='seasonalsubmissionconfig',
            name='current_issue_label_1',
            field=models.CharField(blank=True, help_text="Human-readable issue label, e.g. 'Year 1 - Fall 2025'. Auto-generated.", max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='seasonalsubmissionconfig',
            name='current_issue_label_2',
            field=models.CharField(blank=True, help_text="Alternative/short issue label, e.g. 'Year 1 - Fall Issue'. Auto-generated.", max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='seasonalsubmissionconfig',
            name='theme_description_1',
            field=models.TextField(blank=True, help_text='First paragraph describing the theme (optional).', null=True),
        ),
        migrations.AddField(
            model_name='seasonalsubmissionconfig',
            name='theme_description_2',
            field=models.TextField(blank=True, help_text='Second paragraph describing the theme (optional).', null=True),
        ),
        migrations.AlterField(
            model_name='seasonalsubmissionconfig',
            name='is_active',
            field=models.BooleanField(default=False, help_text='Set to true to make this the currently active submission configuration.'),
        ),
        migrations.AlterField(
            model_name='seasonalsubmissionconfig',
            name='publication_date',
            field=models.DateField(help_text='Planned publication date for the issue (YYYY-MM-DD).'),
        ),
        migrations.AlterField(
            model_name='seasonalsubmissionconfig',
            name='season',
            field=models.CharField(choices=[('Spring', 'Spring'), ('Summer', 'Summer'), ('Fall', 'Fall'), ('Winter', 'Winter')], help_text='Season for this issue (Spring, Summer, Fall, or Winter).', max_length=20),
        ),
        migrations.AlterField(
            model_name='seasonalsubmissionconfig',
            name='seasonal_note',
            field=models.TextField(blank=True, help_text='Optional note or editorial comment about this season/issue.', null=True),
        ),
        migrations.AlterField(
            model_name='seasonalsubmissionconfig',
            name='submission_deadline',
            field=models.DateField(help_text='Final date to accept submissions (YYYY-MM-DD).'),
        ),
        migrations.AlterField(
            model_name='seasonalsubmissionconfig',
            name='theme_alignment',
            field=models.TextField(blank=True, help_text='Short paragraph describing how submissions should align with the theme.', null=True),
        ),
        migrations.AlterField(
            model_name='seasonalsubmissionconfig',
            name='theme_bullet_1',
            field=models.CharField(blank=True, help_text='Bullet point 1 (e.g., Stories of deep devotion...).', max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='seasonalsubmissionconfig',
            name='theme_bullet_2',
            field=models.CharField(blank=True, help_text='Bullet point 2.', max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='seasonalsubmissionconfig',
            name='theme_bullet_3',
            field=models.CharField(blank=True, help_text='Bullet point 3.', max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='seasonalsubmissionconfig',
            name='theme_bullet_4',
            field=models.CharField(blank=True, help_text='Bullet point 4.', max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='seasonalsubmissionconfig',
            name='theme_bullet_5',
            field=models.CharField(blank=True, help_text='Bullet point 5.', max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='seasonalsubmissionconfig',
            name='theme_title',
            field=models.CharField(help_text='Short, human-readable title for the theme.', max_length=200),
        ),
        migrations.AlterField(
            model_name='seasonalsubmissionconfig',
            name='year',
            field=models.PositiveIntegerField(help_text='Calendar year for the issue (e.g., 2025).'),
        ),
    ]
