# Generated by Django 5.2.1 on 2025-05-20 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('woodtech', '0003_alter_magazine_cover_image_alter_magazine_pdf_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='magazine',
            name='season_number',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='magazine',
            name='volume_number',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterUniqueTogether(
            name='magazine',
            unique_together={('volume_number', 'season_number')},
        ),
    ]
