# Generated by Django 5.2.1 on 2025-05-20 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('woodtech', '0004_alter_magazine_season_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='magazine',
            name='page_images',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
