# Generated by Django 5.2.1 on 2025-11-09 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('woodtech', '0004_remove_seasonalsubmissionconfig_current_issue_label_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('banner_title', models.CharField(help_text='Unique title for this banner campaign', max_length=255, unique=True)),
                ('banner_identifier', models.SlugField(blank=True, help_text='Auto-generated unique identifier used for localStorage tracking', max_length=100, unique=True)),
                ('reset_duration_days', models.PositiveIntegerField(default=7, help_text='Number of days after which banner reappears after dismissal')),
                ('is_active', models.BooleanField(default=False, help_text='Only one banner can be active at a time')),
                ('duration_months', models.PositiveIntegerField(default=0, help_text='Duration in months (0 for no time limit)')),
                ('duration_days', models.PositiveIntegerField(default=0, help_text='Additional duration in days')),
                ('auto_deactivate_at', models.DateTimeField(blank=True, help_text='Automatically calculated deactivation date based on duration', null=True)),
                ('desktop_main_text', models.CharField(help_text='Main text displayed on desktop version', max_length=200)),
                ('desktop_link_text', models.CharField(help_text='Clickable text for desktop version', max_length=100)),
                ('desktop_route', models.CharField(choices=[('/', 'Home'), ('/submit', 'Submit Your Work'), ('/contact', 'Contact'), ('/collaborate', 'Collaborate'), ('/issues', 'Issues'), ('/legal', 'Legal'), ('/about', 'About'), ('/faq', 'FAQ'), ('none', 'None')], default='none', help_text='Destination route for desktop click', max_length=20)),
                ('mobile_main_text', models.CharField(help_text='Main text displayed on mobile version', max_length=150)),
                ('mobile_route', models.CharField(choices=[('/', 'Home'), ('/submit', 'Submit Your Work'), ('/contact', 'Contact'), ('/collaborate', 'Collaborate'), ('/issues', 'Issues'), ('/legal', 'Legal'), ('/about', 'About'), ('/faq', 'FAQ'), ('none', 'None')], default='none', help_text='Destination route for mobile click', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('activation_date', models.DateTimeField(blank=True, help_text='When this banner was activated', null=True)),
            ],
            options={
                'verbose_name': 'Banner',
                'verbose_name_plural': 'Banners',
                'ordering': ['-created_at'],
            },
        ),
    ]
