# Generated by Django 5.2.1 on 2025-11-20 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('woodtech', '0005_banner'),
    ]

    operations = [
        migrations.CreateModel(
            name='Conversation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField()),
                ('user_input', models.TextField()),
                ('agent_type', models.CharField(choices=[('classifier', 'Classifier'), ('answer', 'Answer')], max_length=20)),
                ('prompt_tokens', models.IntegerField(default=0)),
                ('completion_tokens', models.IntegerField(default=0)),
                ('total_tokens', models.IntegerField(default=0)),
                ('processing_time', models.FloatField(help_text='Time taken in seconds')),
                ('agent_input', models.TextField(blank=True)),
                ('agent_output', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RemoveIndex(
            model_name='tokenusage',
            name='token_usage_last_up_6ce0dc_idx',
        ),
        migrations.AlterField(
            model_name='tokenusage',
            name='ip_address',
            field=models.GenericIPAddressField(primary_key=True, serialize=False),
        ),
        migrations.AlterModelTable(
            name='tokenusage',
            table=None,
        ),
    ]
