# Generated by Django 5.2.1 on 2025-05-23 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('woodtech', '0006_article'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='user_bio',
            field=models.TextField(blank=True, null=True),
        ),
    ]
