# Generated by Django 5.2.1 on 2025-11-22 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('woodtech', '0006_conversation_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='season',
            field=models.CharField(blank=True, choices=[('winter', 'Winter'), ('spring', 'Spring'), ('summer', 'Summer'), ('fall', 'Fall')], help_text='Season for this article (set manually)', max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='article',
            name='year',
            field=models.PositiveIntegerField(blank=True, help_text='Year for this article (set manually)', null=True),
        ),
    ]
