# Generated by Django 5.2.1 on 2025-11-22 20:13

import django_countries.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('woodtech', '0007_article_season_article_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='country',
            field=django_countries.fields.CountryField(blank=True, help_text="Author's country (optional)", max_length=2, null=True),
        ),
    ]
