# Generated by Django 5.2.1 on 2025-05-26 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('woodtech', '0008_subscriber'),
    ]

    operations = [
        migrations.CreateModel(
            name='Collaborator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('brand_or_organization', models.CharField(max_length=150)),
                ('message', models.TextField(blank=True)),
                ('logo_or_sample', models.FileField(blank=True, null=True, upload_to='uploads/')),
                ('status', models.CharField(choices=[('new', 'New'), ('review', 'In Review'), ('approved', 'Approved'), ('declined', 'Declined')], default='new', max_length=20)),
                ('internal_notes', models.TextField(blank=True)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
