# Generated by Django 5.2.1 on 2025-05-26 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('woodtech', '0009_collaborator'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collaborator',
            name='status',
            field=models.CharField(choices=[('new', 'New'), ('in_review', 'In Review'), ('approved', 'Approved'), ('declined', 'Declined')], default='new', max_length=20),
        ),
    ]
