# Generated by Django 5.2.1 on 2025-06-22 14:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('woodtech', '0010_alter_collaborator_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='country',
        ),
    ]
