# Generated by Django 5.2.1 on 2025-06-26 04:49

import woodtech.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('woodtech', '0011_remove_article_country'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collaborator',
            name='logo_or_sample',
            field=models.FileField(blank=True, null=True, upload_to=woodtech.models.collaborator_upload_path),
        ),
    ]
